services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: postgres:16
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scrapy
      - POSTGRES_USER=scrapy
      - POSTGRES_PASSWORD=scrapy
  dev:
    image: scrapy
    ports:
      - 8000:8000
    container_name: scrapy
    volumes:
      - ${PWD}:/home/scrapy/work
    command: bash -c 'bash --init-file <(echo ". \"/home/scrapy/.bashrc\"; python manage.py runserver 0.0.0.0:8000")'
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    depends_on:
      - db
  celery_dev:
    image: scrapy
    container_name: scrapy_celery
    command: celery -A core worker --loglevel=info
    env_file:
      - .env.dev
    volumes:
      - ${PWD}:/home/scrapy/work
    depends_on:
      - redis
volumes:
  postgres_data:
  redis_data: